config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :datauploaders, :controller => 'data_uploaders', only: [:file_upload, :import, :changetablecolumndetail,
                                                                    :showuploadedschema, :uploadedfile, :uploadfilerecord,
                                                                    :columnexcludeinclude] do
    collection do
      get :fileupload, :action => 'file_upload'
      post :import
      post :fileuploadtoamazon, :action=>'file_upload_to_amazon'
      post :changetablecolumndetail, :action=>'change_table_column_detail'
      get :showuploadedschema, :action => 'show_uploaded_schema'
      get :uploadedfile, :action => 'uploaded_file'
      get :uploadfilerecord, :action=>'upload_file_record'
      get :uploadfilerecordjson, :action=>'upload_file_record_json'
      post :uploadfilerecord, :action=>'upload_file_record'
      delete :columnexcludeinclude, :action=>'column_exclude_include'
      delete :deleteuserfilemappingrecord, :action=>'delete_user_file_mapping_record'
      post :uploadfilecolumnsforrecord, :action=>'upload_file_columns_for_record'
      get :showerrorrecord, :action => 'show_error_record'
      get :restartinsertion, :action => 'restart_insertion'
      get :checkfileuploaded, :action => 'check_file_uploaded'
      delete :deletecompletedatasource, :action => 'delete_complete_data_source'
    end
  end

  resources :recordtrends, :controller => 'trend_analysis', only: [:simple_trend] do
    collection do
      get :simpletrend , :action => 'simple_trend'
    end
  end
  devise_for :users
  root to: 'welcome#welcome'
end

app/views/shared/_navigation.html.erb
<div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Crunch-Insights</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if current_user %>
                <li class="active"> <%= link_to 'Home' , root_path %> </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Upload <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Data Upload' , fileupload_datauploaders_path %> </li>
                    <li><%= link_to 'Uploaded Files' , uploadedfile_datauploaders_path %></li>
                  </ul>
                </li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Edit Profile' ,edit_user_registration_path %> </li>
                    <li ><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
            <% else %>
                <li> <%= link_to 'Sign Up' , new_user_registration_path %> </li>
                <li> <%= link_to 'Sign In' , new_user_session_path %> </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->