config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :datauploaders, :controller => 'data_uploaders', only: [:file_upload, :import, :changetablecolumndetail,
                                                                    :showuploadedschema, :uploadedfile, :uploadfilerecord,
                                                                    :columnexcludeinclude] do
    collection do
      get :fileupload, :action => 'file_upload'
      post :import
      post :fileuploadtoamazon, :action=>'file_upload_to_amazon'
      post :changetablecolumndetail, :action=>'change_table_column_detail'
      get :showuploadedschema, :action => 'show_uploaded_schema'
      get :uploadedfile, :action => 'uploaded_file'
      get :uploadfilerecord, :action=>'upload_file_record'
      get :uploadfilerecordjson, :action=>'upload_file_record_json'
      post :uploadfilerecord, :action=>'upload_file_record'
      delete :columnexcludeinclude, :action=>'column_exclude_include'
      delete :deleteuserfilemappingrecord, :action=>'delete_user_file_mapping_record'
      post :uploadfilecolumnsforrecord, :action=>'upload_file_columns_for_record'
      get :showerrorrecord, :action => 'show_error_record'
      get :restartinsertion, :action => 'restart_insertion'
      get :checkfileuploaded, :action => 'check_file_uploaded'
      delete :deletecompletedatasource, :action => 'delete_complete_data_source'
    end
  end

  resources :recordtrends, :controller => 'trend_analysis', only: [:simple_trend] do
    collection do
      get :simpletrend , :action => 'simple_trend'
    end
  end
  devise_for :users
  root to: 'welcome#welcome'
end

app/controllers/data_uploaders_controller.rb
require 'aws-sdk'
class DataUploadersController < ApplicationController
  respond_to :html, :js, :json
  add_breadcrumb "Home", :root_path, :options => { :title => "Home" }
  def file_upload
    initalize_breadcrumb("File Upload", fileupload_datauploaders_path)
  end
  
  def file_upload_to_amazon
    selected_file_name = params[:selected_file_name]
    puts "*************************************"
    puts selected_file_name    
    table_name= (current_user.id).to_s + DateTime.now.strftime('%Q').downcase.pluralize
    uploaded_file_name = params[:file].original_filename  
    #insert into a record user file mapping ....       
    bucket = S3_BUCKET      
    object = bucket.objects[table_name]

    begin
      byebug
      if selected_file_name != '' && selected_file_name !=nil then
        is_process_complete = DataUploader.delete_existing_data_source(selected_file_name)
      end
      #objecterroe = bucket.objects['error'+table_name]
      object.write(:file => params[:file]) 
      #objecterroe.write(:file => object.read)
      add_file_detail = UserFileMapping.insert_uploaded_file_record(current_user, uploaded_file_name, table_name, Constant.file_upload_status_constants[:file_successfully_uploaded])
      # create a thread for process on file      
      Thread.new do
        process_on_file_row_wise(table_name)
        #process_on_file(table_name)    
      end

      @json_res = {:is_error => false, :error_message => ""}
      respond_to do |format|  
        format.json { render :json => [@json_res]}
      end

    rescue Exception => err
      puts "Error Here ====>>>>>>>>> #{err}"
      add_file_detail = UserFileMapping.insert_uploaded_file_record(current_user, uploaded_file_name, table_name, Constant.file_upload_status_constants[:file_not_uploaded])      
      @json_res = {:is_error => true, :error_message => "Error in file <i>#{uploaded_file_name} </i>upload"}
      respond_to do |format|  
        format.json { render :json => [@json_res]}
      end
    end           
  end 
  # show upload csv generated table schema
  def show_uploaded_schema
    initalize_breadcrumb("Uploaded File(s)", uploadedfile_datauploaders_path)
    @table_name = params[:table_name]
    @uploaded_schema = DataUploader.get_uploaded_schema(@table_name)
    if @uploaded_schema.size > 0 then
      table_column_information = get_user_table_column_info(@table_name)
      @disabled_column  = []
      table_column_information.each do |column_info| 
        if column_info[:is_disable] == true then
          @disabled_column.append(column_info[:column_name])
        end

        if column_info[:money_format] != '' then
          @uploaded_schema.each do |schema|
            if schema[:Field] == column_info[:column_name] then
              schema[:money_symbol] = column_info[:money_format]
              break
            end            
          end
        elsif column_info[:percentage_format] == true then
          @uploaded_schema.each do |schema|
            if schema[:Field] == column_info[:column_name] then
              schema[:is_percentage] = column_info[:percentage_format]
              break
            end
          end
        end
      end

      check_record_uploaded = UserFileMapping.where(:table_name => @table_name).first
      @is_record_uploaded = false
      if check_record_uploaded then
        @is_record_uploaded = check_record_uploaded.is_record_uploaded
      end
      puts @uploaded_schema
      initalize_breadcrumb("Uploaded File Schema", showuploadedschema_datauploaders_path({:table_name => @table_name}))
    else
      redirect_to uploadedfile_datauploaders_path, :flash => { :error => "Table schema not exists" }
    end
  end

  # find uploaded files details
  def uploaded_file
    initalize_breadcrumb("Uploaded File(s)", uploadedfile_datauploaders_path)
    currentUser = current_user.id
    @uploadedFiles = UserFileMapping.where(:user_id =>currentUser )
    respond_with(@uploadedFiles)
  end

  # find uploaded file records
  def upload_file_record
    initalize_breadcrumb("Uploaded File(s)", uploadedfile_datauploaders_path)
    @table_record = {data:[], draw: 1, recordsTotal:"0", recordsFiltered:"0",columns:[]}
    @table_name = params[:table_name]
    @summary = {total_record: 0, success_record: 0, error_record: 0}
    user_file_mappings = UserFileMapping.where(:table_name => @table_name).first
    #
    @summary[:total_record] = user_file_mappings.total_records  ? user_file_mappings.total_records : 0
    @summary[:success_record] = user_file_mappings.success_records  ? user_file_mappings.success_records : 0
    @summary[:error_record] = user_file_mappings.error_records ? user_file_mappings.error_records : 0
    if @summary[:total_record] >= 0 then
      @summary[:success_record] = @summary[:success_record] == 0 ? 0 : ((@summary[:success_record].to_f/@summary[:total_record])*100).round(2)
      @summary[:error_record] = @summary[:error_record] == 0 ? 0 : ((@summary[:error_record].to_f/@summary[:total_record])*100).round(2)
    end
    page_size = 10
    page_index = 0
    draw = 1
    search_value = '' 
    order_column_index=0
    order_column_name =''
    order_type ="ASC"
    if params[:search] != nil then
      search_value = params[:search]["value"]
    end

    if (params[:length])
        page_size = params[:length]
    end

    if (params[:start])
        page_index = params[:start]
    end

    if (params[:draw])
        draw = params[:draw]
        @table_record[:draw]=draw
    end    

    if params[:columns] != nil then
      params[:columns].each do |columns|        
        @table_record[:columns].append(columns[1]["data"])
      end
    end
    if params[:order] != nil then
        params[:order].each do |order|          
         order_column_index = order[1]["column"]
         order_type = order[1]["dir"]         
        end        
    end 
   
    if @table_record[:columns].size > 0      
      order_column_name=@table_record[:columns][order_column_index.to_i]
    end  

    response = DataUploader.get_table_data(@table_name, page_size, page_index, order_column_name,order_type,search_value, @table_record[:columns])
    if response.to_a.size > 0 then        
      table_column_information = get_user_table_column_info(@table_name)
      response.each do |record|
        @table_record[:recordsTotal] = record["totalrecord"]
        @table_record[:recordsFiltered] = record["filterrecord"]
        puts "%%%%%%%%%%%%%%%%%%%%%%%% record %%%%%%%%%%%%%%%%%%%%%%%%%%%%555"
        puts record
        table_column_information.each do |column_info|
          if record.has_key?(column_info[:column_name])
            if column_info[:money_format] != '' then
              record[column_info[:column_name]] = record[column_info[:column_name]].to_s + column_info[:money_format].to_s
            elsif column_info[:percentage_format] == true then
              record[column_info[:column_name]] = record[column_info[:column_name]].to_s + "%"              
            end            
          end
        end

        uploaded_schema = DataUploader.get_uploaded_schema(@table_name)
        uploaded_schema.each do |table_schema|
          if ((record.has_key?(table_schema[:Field])) && (table_schema[:Type] == "bool")) then
            if (record[table_schema[:Field]] == "t") then
              record[table_schema[:Field]] = "TRUE"
            elsif (record[table_schema[:Field]] == "f") then
              record[table_schema[:Field]] = "FALSE"
            end
          end
        end

        @table_record[:data].append(record)
      end     
    end
    initalize_breadcrumb("Uploaded File Record(s)", uploadfilerecord_datauploaders_path)    
    respond_to do |format| 
      format.html 
      format.js  
      format.json { render :json => @table_record}
    end
  end

   # find uploaded file records
  def upload_file_record_json
   initalize_breadcrumb("Uploaded File Record(s)", uploadfilerecord_datauploaders_path) 
    @table_name = params[:table_name]   
    @table_record=[]
    response = DataUploader.get_table_data_without_pagination(@table_name)
    if response.to_a.size > 0 then        
      response.each do |record| 
        @table_record.append(record)
      end     
    end       
    respond_to do |format| 
      format.html       
      format.js  
      format.json { render :json => @table_record}
    end

  end

  def change_table_column_detail
    @uploaded_records=[]
    respond_with(@uploaded_records)
  end

  def column_exclude_include
    table_name = params[:table_name]
    column_name = params[:column_name]
    is_column_disabled = params[:is_column_disabled]
    errors = ""
    update_column_info = UserTableColumnInformation.update_column_information(current_user, is_column_disabled, table_name, column_name)
    if update_column_info.errors.any?
      update_column_info.errors.full_messages.each do |message|
        errors = errors + message + "\n"
      end
    end
    respond_to do |format|
      format.html { redirect_to showuploadedschema_datauploaders_path({:table_name => table_name}), notice: (errors.size ==0 ? "Column detail update Successfully": errors)  }
      format.json { head :no_content }
    end
  end

  def delete_user_file_mapping_record
    table_name = params[:table_name]
    response = DataUploader.check_table_exist(table_name)
    if response.to_a.size > 0 then
      DataUploader.drop_table_if_exist(table_name)
    end
    delete_user_file_mapping_record = UserFileMapping.find_by(:table_name => table_name).destroy
    redirect_to uploadedfile_datauploaders_path, :flash => { :notice => "Data source deleted successfully." }
  end

  # find uploaded file records
  def upload_file_columns_for_record
    @table_columns = {columns: []}
    table_name = params[:table_name] 
    uploaded_schema = DataUploader.get_uploaded_schema(table_name)
    if uploaded_schema.size > 0
        disabled_column = get_user_table_column_info(table_name)

app/helpers/data_uploader_helper.rb
module DataUploaderHelper
end

app/views/data_uploaders/file_upload.html.erb
<h2>Upload CSV for Data Analytics</h2>
<div id="dropzone" class="fade">Drop CSV here</div>
<h3>OR</h3>
<%= form_tag fileuploadtoamazon_datauploaders_path, remote: true, multipart: true, id: 'uploadForm' do %>	
    <div class="row"><div class="col-sm-4"><span><label style="float: left; margin-right: 10px; padding-top: 3px;">Select CSV file: </label><%= file_field_tag :file %><span></div>
    <!-- <div class="col-sm-6"><%= submit_tag "Upload CSV", class:"btn btn-sm btn-primary" %></div> -->
    </div>    
<% end %>
<div class="progress-wrapper">
    <p>Bitrate: <span class="bitrate"></span></p>
    <div class="progress">
      <div class="progress-bar" role="progressbar"> 0%
      </div>
    </div>
</div>  
<div id="div_loading_window" class="modal fade in" style="width: 100% !Important; overflow-y: hidden; height: 100% !Important;">
  <%= image_tag("ajax-loader.gif", :class => "modal-dialog", :style=>"margin: auto  !important; left: 45%  !important; top: 45%  !important; width: auto !important;") %>
  <div class="modal-body" style="color: #FF1919 !important; font-size: 20px !important; font-weight: bold !important; left: 35% !important; top: 45% !important; width: auto !important;">
   <p>Please wait while upload is in progress!!!!!</p>
  </div>
</div>
<div id="possibleMatch-model-popup" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" style="width: 650px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Please select a file for overwrite.</h4>
      </div>
      <div class="modal-body">
        <table id="uploadedSchema" class="table table-striped table-bordered dataTable table-hover table-highlight">
          <thead>
            <tr>              
              <th>Upload File</th>
              <th>Data Source</th>
              <th>Upload Date</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag('datauploaders.js') %>

app/views/data_uploaders/show_uploaded_schema.html.erb
<h2>Uploaded Data Schema</h2>
<h4>Fields included in Data Insight</h4>
<div class="row">
  <% if @is_record_uploaded then %>
      <%= link_to "Trend Analysis", simpletrend_recordtrends_path({:table_name=> @table_name}), :type=>"button", :class=>"btn btn-sm btn-primary", :style=>"float: right; margin-bottom: 20px; margin-right: 15px;", :onclick => "show_loading_window();" %>
  <% else %>
      <button type="button" class="btn btn-sm btn-primary" onclick="show_message('Data upload is still in progress. Please refresh the page for latest status', 'info', this, false);" style="float: right; margin-bottom: 20px; margin-right: 15px;">Trend Analysis</button>
  <% end %>  
</div>
<table id="enabledUploadedSchema" class="table table-striped table-bordered custom_table table-hover table-highlight table-checkable">
  <thead>
      <tr>
        <th style="width: 250px">Column Name</th>
        <th style="width: 250px">Type</th>
        <th>Null</th>
        <th>Unique</th>
        <th style="width: 100px">Action</th>
      </tr>
  </thead>
  <tbody>
    <% if @uploaded_schema.size > 0 then %>
        <% @uploaded_schema.each do |schema| %>
          <% if !(@disabled_column.include? schema[:Field]) %>
              <tr>
                <td is_editable = "yes">
                  <div is_default = "yes"><%= schema[:Field] %></div>
                  <div class="form-group" style="margin-bottom: 0;display: none">
                    <input type="text" class="form-control" value="<%= schema[:Field] %>">
                  </div>
                </td>
                <td is_editable ="yes">
                  <div is_default ="yes">
                    <%if schema[:Type] == "numeric" then %>
                      decimal
                      <%if schema[:money_symbol] != '' then %>
                        (Money Format - <%= schema[:money_symbol]%>)
                      <%elsif schema[:is_percentage] == true then %>
                        (Percentage/Rate Value)
                      <% end %>
                    <%elsif schema[:Type] == "timestamp" then %>datetime
                    <%elsif schema[:Type] == "bool" then %>boolean
                    <%elsif schema[:Type].include?'int' then %>integer
                        <% else %><%= schema[:Type] %>
                    <% end %>
                  </div>
                  <div class="form-group" style="margin-bottom: 0; display: none">
                    <select class="form-control">
                      <option <%= ((schema[:Type]).include? "varchar")? "selected" : "" %>>string</option>
                      <option <%= ((schema[:Type]).include? "int")? "selected" : ""%> >integer</option>
                      <option <%= ((schema[:Type]).include? "numeric")? "selected" : ""%> >decimal</option>
                      <option <%= ((schema[:Type]).include? "timestamp")? "selected" : "" %> >datetime</option>
                      <option <%= ((schema[:Type]).include? "bool")? "selected": "" %> >boolean</option>
                    </select>
                  </div>
                </td>
                <td><%= schema[:Null] %></td>
                <td>
                  <%= schema[:Key] %>
                </td>
                <td is_button_column = "yes">
                  <div>
                    <!--<button type="button" class="btn btn-sm btn-primary" button_type="edit" onclick="edit_button_click(this);">Edit</button>-->
                    <%= link_to "Save", changetablecolumndetail_datauploaders_path({:column_name => schema[:Field],:table_name=> @table_name,:is_column_disabled=>true}), data: { confirm: 'Are you sure?' },:button_type=>"save",:style=>"display: none",:type=>"button",:class=>"btn btn-sm btn-success" %>
                    <%= link_to "Exclude", columnexcludeinclude_datauploaders_path({:column_name => schema[:Field], :table_name=> @table_name, :is_column_disabled=>true}), method: :delete, data: { confirm: 'Are you sure?' }, :type=>"button", :class=>"btn btn-sm btn-danger" %>
                  </div>
                </td>
              </tr>
          <% end %>
        <% end %>
    <% end %>
  </tbody>
</table>
<div id="div_loading_window" class="modal fade in" style="width: 100% !Important; overflow-y: hidden; height: 100% !Important;">
  <%= image_tag("ajax-loader.gif", :class => "modal-dialog", :style=>"margin: auto  !important; left: 45%  !important; top: 45%  !important; width: auto !important;") %>
  <div class="modal-body" style="color: #FF1919 !important; font-size: 20px !important; font-weight: bold !important; left: 35% !important; top: 45% !important; width: auto !important;">
    <p>Please wait while analysis is in progress!!!!!</p>
  </div>
</div>
<% if @disabled_column.size > 0 then %>
    <h4>Fields excluded in Data Insight</h4>
    <table id="disabledUploadedSchema" class="table table-striped custom_table table-bordered dataTable table-hover table-highlight table-checkable">
      <thead>
      <tr>
        <th style="width: 250px">Column Name</th>
        <th style="width: 250px">Type</th>
        <th>Null</th>
        <th>Unique</th>
        <th style="width: 90px">Action</th>
      </tr>
      </thead>
      <tbody>
          <% if @uploaded_schema.size > 0 then %>
              <% @uploaded_schema.each do |schema| %>
                  <% if @disabled_column.include? schema[:Field] %>
                      <tr>
                        <td><%= schema[:Field] %></td>
                        <td>
                          <%if schema[:Type] == "numeric" then %>
                            decimal
                            <%if schema[:money_symbol] != '' then %>
                              (Money Format - <%= schema[:money_symbol]%>)
                            <%elsif schema[:is_percentage] == true then %>
                              (Percentage/Rate Value)
                            <% end %>
                          <%elsif schema[:Type] == "timestamp" then %>datetime
                          <%elsif schema[:Type] == "bool" then %>boolean
                          <%elsif schema[:Type].include?'int' then %>integer
                          <% else %><%= schema[:Type] %>
                          <% end %>
                        </td>
                        <td><%= schema[:Null] %></td>
                        <td><%= schema[:Key] %></td>
                        <td>
                          <div>
                            <%= link_to "Include", columnexcludeinclude_datauploaders_path({:column_name => schema[:Field], :table_name=> @table_name, :is_column_disabled=>false}), method: :delete, data: { confirm: 'Are you sure?' }, :type=>"button", :class=>"btn btn-sm btn-success" %>
                          </div>
                        </td>
                      </tr>
                  <% end %>
              <% end %>
          <% end %>
      </tbody>
    </table>
<% end %>
<%= javascript_include_tag('datauploaders.js') %>

app/views/data_uploaders/upload_file_record.html.erb
<h2>File Records</h2>	
<% if @summary[:total_record] >= 0 then %>
	<% if @summary[:success_record] == 0 then %>
		<div class="alert alert-warning">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<p><strong>Summary: </strong>All records in the CSV are discarded as error.
			</p>
		</div>
	<% elsif @summary[:success_record] == 100 then %>
		<div class="alert alert-success">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<p><strong>Summary: </strong>All records in the CSV are successfully processed</p>
		</div>
	<% else %>
		<div class="alert alert-info">
			<button data-dismiss="alert" class="close" type="button">×</button>
				<p><strong>Summary: </strong>Showing <%= @summary[:success_record] %> % successfully processed records out of <%= @summary[:total_record] %> records. Other <%= @summary[:error_record] %> % records are discarded as error. To view error records, Click <%= link_to "here", showerrorrecord_datauploaders_path({:table_name => @table_name, :is_schema_error => false}), :type=>"button", :class=>"link" %>					
				<p>
		</div>
	<% end %>
<% end %>
<input type="hidden" id="page_params" value=<%= @table_name %>>
<table id="uploadedRecords" class="table table-striped table-bordered dataTable" cellspacing="0" width="100%">     
</table>
<%= javascript_include_tag('datauploaders.js') %>
<%= javascript_include_tag('custom_pagination.js') %>

app/views/data_uploaders/upload_file_record_json.html.erb
<h3>Upload file record in json fromat</h3>
<div  style="max-height: 10px;">
	<% @table_record.each do |table|%>
	<div class="panel-body">
		<%=table.to_yaml %></br>
	</div>	
	<% end %>
</div>

app/views/data_uploaders/uploaded_file.html.erb
<h2>Uploaded Files</h2>
<table id="uploadedSchema" class="table table-striped table-bordered dataTable custom_table table-hover table-highlight table-checkable">
  <thead>
    <tr>
      <th style="width: 250px">Upload File</th>
      <th style="width: 200px">Data Source</th>
      <th style="width: 150px">Upload Date</th>
      <th style="width: 250px">Upload Summary </th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% if @uploadedFiles.size > 0 then %>
      <% @uploadedFiles.each do |record| %>
        <tr>
          <td><%= record.file_name %></td>
          <td><%= record.table_name %></td>
          <td><%= (record.created_on).strftime("%m/%d/%Y") %></td>
          <td>
            <ul style="margin: 0; padding: 0 0 0 15px;">
              <li>Total Records: <%= record.total_records %></li>
              <li>Successfully Processed: <%= record.success_records %></li>
              <li>Error Records: <%= record.error_records %></li>
            </ul>
          </td>
          <td style="text-align: center;">
          	<div>
              <% if record.file_upload_status != Constant.file_upload_status_constants[:file_uploaded_with_no_record] then %>
              	<% if record.is_table_created then %>
                  <%= link_to "Schema", showuploadedschema_datauploaders_path({:table_name => (record.table_name)}), :type=>"button", :class=>"btn btn-sm btn-warning"%>
                  <% if record.is_record_uploaded then %>
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-list" aria-hidden="true"></button>
                      <button type="button" class="btn btn-sm btn-primary dropdown-toggle " data-toggle="dropdown" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                      </button>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Show Records", uploadfilerecord_datauploaders_path({:table_name => (record.table_name)}), :type=>"button", :class=>"link" %></li>
                        <% if record.has_error_record then %>							    
                          <li><%= link_to "Download Error Record", showerrorrecord_datauploaders_path(:table_name => (record.table_name), :is_schema_error => false, :format =>'csv'), :type=>"button", :class=>"link" %>
                          </li>
                        <% end %>					    						    
                      </ul>                    
                    </div>
                    <%= link_to "Remove", deletecompletedatasource_datauploaders_path({:table_name => (record.table_name)}), method: :delete,:type=>"button", :class=>"btn btn-sm btn-danger"%>                       
                  <% else %>
                  	<div class="btn-group">
  	                    <button type="button" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-list" aria-hidden="true"></button>
  	                    <button type="button" class="btn btn-sm btn-primary dropdown-toggle " data-toggle="dropdown" aria-expanded="false">
  	                      <span class="caret"></span>
  	                      <span class="sr-only">Toggle Dropdown</span>
  	                    </button>
  	                    <ul class="dropdown-menu" role="menu">
  	                    	<li>
  	                    		<% if record.file_upload_status != Constant.file_upload_status_constants[:file_record_insert_error] then %>
  	                          <a type="button" class="link" onclick="show_message('Data upload is still in progress. Please refresh the page for latest status', 'info', this, false);">Show Records</a>
  	                        <% else %>
  	                        	<%= (link_to "here", restartinsertion_datauploaders_path({:table_name => (record.table_name)}), :style => "display: none", :class => "include_in_message" )%>
  	                        	<a type="button" class="link" onclick="show_message('There was an error in your previous data upload. In order to process it again, click ', 'error', this, true);">Show Records</a>
  	                        <% end %>
  	                    	</li>					    
  	                    </ul>
    				        </div>
                    <% if record.file_upload_status == Constant.file_upload_status_constants[:file_record_insert_error] then %>
                      <%= link_to "Remove", deletecompletedatasource_datauploaders_path({:table_name => (record.table_name)}), method: :delete,:type=>"button", :class=>"btn btn-sm btn-danger"%>
                    <% end %>
                  <% end %>
                <% else %>
                	<% if record.file_upload_status == Constant.file_upload_status_constants[:file_successfully_uploaded] then %>
                		<button type="button" class="btn btn-sm btn-warning" onclick="show_message('We are still analyzing the data types of the columns in CSV. Please refresh the page for latest status. ', 'info', this, false);">Schema</button>
                	<% elsif record.file_upload_status == Constant.file_upload_status_constants[:file_uploaded_with_error] then %>
                		<%= (link_to "here", showerrorrecord_datauploaders_path({:table_name => (record.table_name), :is_schema_error => true}), :style => "display: none", :class => "include_in_message", :onclick => "show_loading_window();" )%>
                		<button type="button" class="btn btn-sm btn-warning" onclick="show_message('File was not successfully analyzed. For more information, Click ', 'error', this, true);">Schema</button>
                	<% elsif record.file_upload_status == Constant.file_upload_status_constants[:file_not_uploaded] then %>
                		<%= (link_to "here", deleteuserfilemappingrecord_datauploaders_path({:table_name => (record.table_name)}), :method => :delete, :style => "display: none", :class => "include_in_message" )%>
                  		<button type="button" class="btn btn-sm btn-warning" onclick="show_message('There was an error in your previous upload. Please upload your file again and if you want to delete this entry from history please click ', 'error', this, true);">Schema</button>
                	<% end %>  
                <% end %> 
              <% else %>
                <button type="button" class="btn btn-sm btn-warning" onclick="show_message('There were no records in the csv or csv contain all error records. Thus, it is discarded and not processed. ', 'error', this, false);">Schema</button>
                <%= link_to "Remove", deletecompletedatasource_datauploaders_path({:table_name => (record.table_name)}), method: :delete,:type=>"button", :class=>"btn btn-sm btn-danger"%>
              <% end %>              
          	</div>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<div id="div_loading_window" class="modal fade in" style="width: 100% !Important; overflow-y: hidden; height: 100% !Important;">
  <%= image_tag("ajax-loader.gif", :class => "modal-dialog", :style=>"margin: auto  !important; left: 45%  !important; top: 45%  !important; width: auto !important;") %>
  <div class="modal-body" style="color: #FF1919 !important; font-size: 20px !important; font-weight: bold !important; left: 35% !important; top: 45% !important; width: auto !important;">
     <p>Please wait while we retrieve your result!!!!!</p>
  </div>
</div>
<%= javascript_include_tag('datauploaders.js') %>